/**
 * ui-texts.js
 *
 * Provides static UI text labels and messages for the frontend application.
 * - Centralizes all UI strings for easy translation and maintenance.
 * - Used by app.js and components to display consistent text.
 * Usage: Import uiTexts where UI labels/messages are needed.
 */

// Static UI texts for the app
export const uiTexts = {
  appTitle: "DMT - Dictionary Management Tool",
  accountButton: "Account",
  userLabel: "User:",
  rolesLabel: "Dictionary Name - Role Name:",
    dictionaryLabel: "Dictionary",
    dictionaryVersionLabel: "Dictionary Version",
    showVersionDetails: "Versions",
  editDictionary: "Edit",
  save: "Save",
  publish: "Publish",
  discard: "Discard",
  filtersOpen: "Filters",
  previous: "Previous",
  next: "Next",
  showRowButton: "Show",
  discardDialogTitle: "Discard changes",
  discardDialogIntro: "Are you sure you want to discard changes?",
  discardDialogKeepEditing: "Keep editing",
  discardDialogConfirm: "Discard",
  saveDialogTitle: "Save changes",
  saveDialogIntro: "Are you sure you want to save changes?",
  saveDialogBack: "Back",
  saveDialogConfirm: "Save",
  discardAllDialogTitle: "Discard all changes",
  discardAllDialogIntro: "Are you sure you want to discard all changes?",
  discardAllDialogBack: "Back",
  discardAllDialogConfirm: "Discard all",
    versionDetailsTitle: "Version History",
  versionDetailsClose: "Close",
  versionDetailsLoadError: "Failed to load version details.",
  errorDetailsTitle: "Error",
  errorDetailsCopy: "Copy details",
  errorDetailsClose: "Close",
  filtersDialogTitle: "Filters",
  filtersDialogIntro: "",
  filtersAddRule: "Add Rule",
  filtersApply: "Apply",
  filtersApplyClose: "Apply & Close",
  filtersClear: "Clear",
  filtersClose: "Close",
  dictionarySelectorAriaLabel: "Select dictionary",
  dictionaryVersionSelectorAriaLabel: "Select dictionary version",
  rowsInitial: "No data",
  pageInfoInitial: "Page: 0/0",
  currentDictionaryNone: "No Dictionary Selected",
  currentDictionaryVersionShort: "ver.",
  filtersSummaryNone: "No Active Filters",
  filtersColumnLabel: "Column",
  filtersValueLabel: "Value",
  filtersValuePlaceholder: "Enter value",
  filtersRemoveRule: "Remove",
  filtersEmpty: "No filter rules.",
  filtersNoColumns: "Load dictionary rows first to choose columns.",
  filtersDiscardDialogTitle: "Discard filter changes",
  filtersDiscardDialogIntro: "Unsaved filter changes were detected:",
  filtersDiscardDialogKeepEditing: "Keep editing",
  filtersDiscardDialogConfirm: "Discard changes",
  selectDictionaryOption: "Select dictionary",
  selectDictionaryVersionOption: "Select version",
  dictionaryVersionDisabledOption: "Versions unavailable",
  dictionaryVersionLoadingOption: "Loading versions...",
  dictionaryVersionEmptyOption: "No versions",
  loadingData: "Loading data...",
  selectDictionaryPrompt: "Select a dictionary to view data",
  selectDictionaryVersionPrompt: "Select dictionary version",
  noRowsReturned: "No data to display",
  noRolesLoaded: "No roles",
  emptyValue: "(empty)"
};