/**
 * ui-texts.js
 *
 * Provides static UI text labels and messages for the frontend application.
 * - Centralizes all UI strings for easy translation and maintenance.
 * - Used by app.js and components to display consistent text.
 * Usage: Import uiTexts where UI labels/messages are needed.
 */

// Static UI texts for the app
export const uiTexts = {
  appTitle: "DMT - Dictionary Management Tool",
  accountButton: "Account",
  signOutButton: "Signout",
  userLabel: "User:",
  rolesLabel: "Dictionary Name - Role Name:",
    dictionaryLabel: "Dictionary",
    dictionaryVersionLabel: "Dictionary Version",
    showVersionDetails: "Versions",
  editDictionary: "Edit",
  save: "Complete",
  publish: "Publish",
  discard: "Discard",
  filtersOpen: "Filters",
  previous: "Previous",
  next: "Next",
  showRowButton: "Show",
  discardDialogTitle: "Discard changes",
  discardDialogIntro: "Are you sure you want to discard changes?",
  discardDialogKeepEditing: "Keep editing",
  discardDialogConfirm: "Discard",
  saveDialogTitle: "Complete changes",
  saveDialogIntro: "Are you sure you want to complete changes?",
  saveDialogBack: "Back",
  saveDialogConfirm: "Complete",
  discardAllDialogTitle: "Discard all changes",
  discardAllDialogIntro: "Are you sure you want to discard all changes?",
  discardAllDialogBack: "Back",
  discardAllDialogConfirm: "Discard all",
    versionDetailsTitle: "Version History",
  versionDetailsClose: "Close",
  versionDetailsLoadError: "Failed to load version details.",
  errorDetailsTitle: "Error",
  errorDetailsCopy: "Copy details",
  errorDetailsClose: "Close",
  filtersDialogTitle: "Filters",
  filtersDialogIntro: "",
  filtersAddRule: "Add Rule",
  filtersApply: "Apply",
  filtersApplyClose: "Apply & Close",
  filtersClear: "Clear",
  filtersClose: "Close",
  checkOutConfirmTitle: "Confirmation",
  checkOutConfirmButton: "Confirm",
  checkOutCancelButton: "Cancel",
  checkOutConfirmMessage: "Confirming this action will lock the dictionary for editing by other users.",
  checkOutExistsOtherUserMessage: "Dictionary is currently in edit mode (check out) by user: {userLogin}.<br><br>Please contact this user to confirm when the Edit mode for this Dictionary will be completed or published.",
  checkOutExistsCurrentUserMessage: "You've already edited the Dictionary.<br><br>You can access it by selecting the version: {versionName} from the 'Dictionary Version' list.",
  returningToCheckoutMessage: "You are returning to change the dictionary you previously edited (checked out).",
  dictionarySelectorAriaLabel: "Select dictionary",
  dictionaryVersionSelectorAriaLabel: "Select dictionary version",
  rowsInitial: "No data",
  pageInfoInitial: "Page: 0/0",
  currentDictionaryNone: "No Dictionary Selected",
  currentDictionaryVersionShort: "ver.",
  filtersSummaryNone: "No Active Filters",
  filtersColumnLabel: "Column",
  filtersValueLabel: "Value",
  filtersValuePlaceholder: "Enter value",
  filtersRemoveRule: "Remove",
  filtersEmpty: "No filter rules.",
  filtersNoColumns: "Load dictionary rows first to choose columns.",
  filtersDiscardDialogTitle: "Discard filter changes",
  filtersDiscardDialogIntro: "Unsaved filter changes were detected:",
  filtersDiscardDialogKeepEditing: "Keep editing",
  filtersDiscardDialogConfirm: "Discard changes",
  selectDictionaryOption: "Select dictionary",
  selectDictionaryVersionOption: "Select version",
  dictionaryVersionDisabledOption: "Versions unavailable",
  dictionaryVersionLoadingOption: "Loading versions...",
  dictionaryVersionEmptyOption: "No versions",
  loadingData: "Loading data...",
  selectDictionaryPrompt: "Select a dictionary to view data",
  selectDictionaryVersionPrompt: "Select dictionary version",
  noRowsReturned: "No data to display",
  noRolesLoaded: "No roles",
  emptyValue: "(empty)",
  saveAndClose: "Complete & Close",
  closeButton: "Close",
  recordDialogTitlePrefix: "Record for: ",
  recordDialogVersionPrefix: "ver.",
  recordNoFields: "No fields to display.",
  recordCloseUnsavedPrompt: "Unsaved changes were detected. Are you sure you want to discard these changes?",
  pageLabel: "Page",
  rowsLabel: "Rows",
  tableActionHeader: "Action",
  loginTitle: "DMT",
  loginSubtitle: "Dictionary Management Tool",
  loginLabel: "Login:",
  loginButton: "Login",
  loginErrorNotFound: "Access Denied.\nLogin is not existing.",
  loginErrorNoRole: "Access denied.\nUser does not have DICTIONARY_READER or DICTIONARY_UPDATER role.",
  loginErrorGeneral: "Could not validate login. Please try again.",
  notImplementedTitle: "Information",
  notImplementedMessage: "This feature is not implemented yet.",
  copied: "✓ Copied",
  loadError: "Error",
  userLoadError: "Error",
  readerNoPermissionLine1: "The DICTIONARY_READER role doesn't have permissions to edit the Dictionary.",
  readerNoPermissionUserManagerLine3: "You have USER_MANAGER role, so you can change Your permissions.",
  readerNoPermissionNonManagerLine3: "Please contact someone with the USER_MANAGER role to change Your permissions:",
  noUserManagersFound: "- No USER_MANAGER users found.",
  addRowSave: "Add",
  addRowSaveAndClose: "Add & Close",
  addRowClear: "Clear",
  addRowAutoValue: "Auto",
  addRowEmptyError: "At least one editable field is required to add a new row.",
  addRowSaveDialogIntro: "Are you sure you want to add this row?",
  newRecordDialogTitlePrefix: "Add record for: "
};